name: Tests

on:
  push:
    branches: [master, v4]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.1"
          - "8.2"
        database:
          - mariadb
          - mysql

    name: Testing PHP ${{ matrix.php }} with ${{ matrix.database }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          distribution: ${{ matrix.database }}

      - name: Install dependencies
        run: composer install

      - name: Execute tests (Laravel/Lumen)
        run: composer test
